-- ============================================================
-- Run this in Supabase SQL Editor → SQL Editor → New query
-- ============================================================

-- Stage Zero now creates public profiles only after the auth flow is verified.
-- This avoids creating a "real" app account before the user finishes the
-- email verification step.
--
-- If you previously installed the old trigger, remove it before applying the
-- app flow below:
--   DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
--   DROP FUNCTION IF EXISTS public.handle_new_user();
--
-- The application now creates rows in public.users from:
--   - /app/auth/verify-email after OTP verification
--   - /app/auth/callback for verified OAuth sign-ins
--   - /app/(public)/login only after a confirmed login session exists
